development:
  local: true
  baseURL: 'http://localhost:3000/'
  facebook:
    apiKey: "your apiKey"
    secret: "your secret"
    label: "Facebook"
  google:
    clientID: "your clientID"
    secret: "your secret"
  twitter:
    apiKey: "your apiKey"
    secret: "your secret"
production:
  baseURL: 'http://s-vorontsov.rhcloud.com/'
  facebook:
    apiKey: "your apiKey"
    secret: "your secret"
    label: "Facebook"
  google:
    clientID: "your clientID"
    secret: "your secret"
  twitter:
    apiKey: "your apiKey"
    secret: "your secret"